foo:
  value: bar


com:
  example:
    config-props:
      my-property: applicationdevchange

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
