foo:
  value: bar


com:
  example:
    config-props:
      my-property: allapplicationdefaultdevvalue

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false
