foo:
  value: bar


com:
  example:
    config-props:
      my-property: allapplicationdefaultremotevalue

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false


myconfig:
  client: placeholdevalueusingvalueannotationfromremotedevprofile
