com:
  example:
    config-props:
      my-property: springconfigexampl

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true


      
      
